create extension if not exists pgcrypto;

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users(id) on delete set null,
  login text not null unique,
  surname text not null,
  name text not null,
  class_name text not null,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.students add column if not exists auth_user_id uuid unique references auth.users(id) on delete set null;
alter table public.students add column if not exists login text;
alter table public.students add column if not exists surname text;
alter table public.students add column if not exists name text;
alter table public.students add column if not exists class_name text;
alter table public.students add column if not exists avatar_url text;
alter table public.students add column if not exists created_at timestamptz not null default now();
alter table public.students add column if not exists updated_at timestamptz not null default now();
create unique index if not exists students_login_unique_idx on public.students(login) where login is not null and login <> '';

create table if not exists public.staff_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('staff', 'admin')),
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.staff_profiles add column if not exists role text;
alter table public.staff_profiles add column if not exists display_name text;
alter table public.staff_profiles add column if not exists created_at timestamptz not null default now();
alter table public.staff_profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.messages (
  id text primary key,
  case_id text not null,
  student_id uuid references public.students(id) on delete cascade,
  author_role text not null check (author_role in ('student', 'fox', 'ai', 'staff', 'system')),
  body text not null,
  case_status text check (case_status in ('new', 'in_progress', 'open', 'closed')),
  urgent boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.messages add column if not exists case_id text;
alter table public.messages add column if not exists student_id uuid references public.students(id) on delete cascade;
alter table public.messages add column if not exists author_role text;
alter table public.messages add column if not exists body text;
alter table public.messages add column if not exists case_status text;
alter table public.messages add column if not exists urgent boolean not null default false;
alter table public.messages add column if not exists created_at timestamptz not null default now();

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  student_id uuid references public.students(id) on delete set null,
  case_id text,
  message_id text references public.messages(id) on delete set null,
  alert_type text not null,
  status text not null default 'new' check (status in ('new', 'seen', 'in_progress', 'closed')),
  summary_for_adult text,
  source text not null default 'client',
  handled_by uuid references public.staff_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.alerts add column if not exists student_id uuid references public.students(id) on delete set null;
alter table public.alerts add column if not exists case_id text;
alter table public.alerts add column if not exists message_id text references public.messages(id) on delete set null;
alter table public.alerts add column if not exists alert_type text;
alter table public.alerts add column if not exists status text not null default 'new';
alter table public.alerts add column if not exists summary_for_adult text;
alter table public.alerts add column if not exists source text not null default 'client';
alter table public.alerts add column if not exists handled_by uuid references public.staff_profiles(id) on delete set null;
alter table public.alerts add column if not exists created_at timestamptz not null default now();
alter table public.alerts add column if not exists updated_at timestamptz not null default now();

create index if not exists students_auth_user_id_idx on public.students(auth_user_id);
create index if not exists messages_case_id_idx on public.messages(case_id);
create index if not exists messages_student_id_created_at_idx on public.messages(student_id, created_at);
create index if not exists alerts_status_created_at_idx on public.alerts(status, created_at desc);
create index if not exists alerts_student_id_idx on public.alerts(student_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists students_touch_updated_at on public.students;
create trigger students_touch_updated_at
before update on public.students
for each row execute function public.touch_updated_at();

drop trigger if exists staff_profiles_touch_updated_at on public.staff_profiles;
create trigger staff_profiles_touch_updated_at
before update on public.staff_profiles
for each row execute function public.touch_updated_at();

drop trigger if exists alerts_touch_updated_at on public.alerts;
create trigger alerts_touch_updated_at
before update on public.alerts
for each row execute function public.touch_updated_at();

create or replace function public.current_staff_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.staff_profiles where id = auth.uid()
$$;

create or replace function public.is_staff_or_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_staff_role() in ('staff', 'admin'), false)
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_staff_role() = 'admin', false)
$$;

alter table public.students enable row level security;
alter table public.staff_profiles enable row level security;
alter table public.messages enable row level security;
alter table public.alerts enable row level security;

drop policy if exists "students_select_own_or_staff" on public.students;
create policy "students_select_own_or_staff"
on public.students for select
using (auth_user_id = auth.uid() or public.is_staff_or_admin());

drop policy if exists "students_insert_own" on public.students;
create policy "students_insert_own"
on public.students for insert
with check (auth_user_id = auth.uid());

drop policy if exists "students_update_own_or_staff" on public.students;
create policy "students_update_own_or_staff"
on public.students for update
using (auth_user_id = auth.uid() or public.is_staff_or_admin())
with check (auth_user_id = auth.uid() or public.is_staff_or_admin());

drop policy if exists "staff_profiles_select_own_or_admin" on public.staff_profiles;
create policy "staff_profiles_select_own_or_admin"
on public.staff_profiles for select
using (id = auth.uid() or public.is_admin());

drop policy if exists "staff_profiles_admin_insert" on public.staff_profiles;
create policy "staff_profiles_admin_insert"
on public.staff_profiles for insert
with check (public.is_admin());

drop policy if exists "staff_profiles_admin_update" on public.staff_profiles;
create policy "staff_profiles_admin_update"
on public.staff_profiles for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "messages_select_own_or_staff" on public.messages;
create policy "messages_select_own_or_staff"
on public.messages for select
using (
  public.is_staff_or_admin()
  or exists (
    select 1 from public.students s
    where s.id = messages.student_id and s.auth_user_id = auth.uid()
  )
);

drop policy if exists "messages_insert_own_or_staff" on public.messages;
create policy "messages_insert_own_or_staff"
on public.messages for insert
with check (
  public.is_staff_or_admin()
  or exists (
    select 1 from public.students s
    where s.id = messages.student_id and s.auth_user_id = auth.uid()
  )
);

drop policy if exists "messages_update_staff_only" on public.messages;
create policy "messages_update_staff_only"
on public.messages for update
using (public.is_staff_or_admin())
with check (public.is_staff_or_admin());

drop policy if exists "alerts_select_own_or_staff" on public.alerts;
create policy "alerts_select_own_or_staff"
on public.alerts for select
using (
  public.is_staff_or_admin()
  or exists (
    select 1 from public.students s
    where s.id = alerts.student_id and s.auth_user_id = auth.uid()
  )
);

drop policy if exists "alerts_insert_own_or_staff" on public.alerts;
create policy "alerts_insert_own_or_staff"
on public.alerts for insert
with check (
  public.is_staff_or_admin()
  or exists (
    select 1 from public.students s
    where s.id = alerts.student_id and s.auth_user_id = auth.uid()
  )
);

drop policy if exists "alerts_update_staff_only" on public.alerts;
create policy "alerts_update_staff_only"
on public.alerts for update
using (public.is_staff_or_admin())
with check (public.is_staff_or_admin());

drop policy if exists "alerts_delete_admin_only" on public.alerts;
create policy "alerts_delete_admin_only"
on public.alerts for delete
using (public.is_admin());
